const AdminActionType = {
    FETCH_RIDERS_PENDING: 'FETCH_RIDERS_PENDING',
    FETCH_RIDERS_FAILED: 'FETCH_RIDERS_FAILED',
    FETCH_RIDERS_SUCCESS: 'FETCH_RIDERS_SUCCESS'
}

export default AdminActionType