const AdminActionType = {
    FETCH_RIDERS_PENDING: 'FETCH_RIDERS_PENDING',
    FETCH_RIDERS_FAILED: 'FETCH_RIDERS_FAILED',
    FETCH_RIDERS_SUCCESS: 'FETCH_RIDERS_SUCCESS',
    DELETE_RIDER_SUCCESS: 'DELETE_RIDER_SUCCESS',
    DELETE_RIDER_PENDING: 'DELETE_RIDER_PENDING',
    DELETE_RIDER_FAILED: 'DELETE_RIDER_FAILED',
    CREATE_RIDER_SUCCESS: 'CREATE_RIDER_SUCCESS',
    CREATE_RIDER_PENDING: 'CREATE_RIDER_PENDING',
    CREATE_RIDER_FAILED: 'CREATE_RIDER_FAILED',
    UPDATE_TIMETABLE_SUCCESS: 'UPDATE_TIMETABLE_SUCCESS',
    UPDATE_TIMETABLE_PENDING: 'UPDATE_TIMETABLE_PENDING',
    UPDATE_TIMETABLE_FAILED: 'UPDATE_TIMETABLE_FAILED',
    FETCH_TIMETABLE_SUCCESS: 'FETCH_TIMETABLE_SUCCESS',
    FETCH_TIMETABLE_PENDING: 'FETCH_TIMETABLE_PENDING',
    FETCH_TIMETABLE_FAILED: 'FETCH_TIMETABLE_FAILED',

}

export default AdminActionType