const CatalogOperationType = {
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',
    CREATE_PRODUCT_PENDING: 'CREATE_PRODUCT_PENDING',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',
    UPDATE_PRODUCT_PENDING: 'UPDATE_PRODUCT_PENDING',
    RESET_STATE: 'RESET_STATE'

}

export default CatalogOperationType