const CatalogOperationType = {
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',
    CREATE_PRODUCT_PENDING: 'CREATE_PRODUCT_PENDING',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',
    UPDATE_PRODUCT_PENDING: 'UPDATE_PRODUCT_PENDING',
    REMOVE_PRODUCT_SUCCESS: 'REMOVE_PRODUCT_SUCCESS',
    REMOVE_PRODUCT_FAILED: 'REMOVE_PRODUCT_FAILED',
    REMOVE_PRODUCT_PENDING: 'REMOVE_PRODUCT_PENDING',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILED: 'CREATE_CATEGORY_FAILED',
    CREATE_CATEGORY_PENDING: 'CREATE_CATEGORY_PENDING',
    REMOVE_CATEGORY_SUCCESS: 'REMOVE_CATEGORY_SUCCESS',
    REMOVE_CATEGORY_FAILED: 'REMOVE_CATEGORY_FAILED',
    REMOVE_CATEGORY_PENDING: 'REMOVE_CATEGORY_PENDING',
    RESET_STATE: 'RESET_CATALOG_OPERATION_STATE'
}

export default CatalogOperationType