const CatalogActionType = {
    FETCH_CATEGORIES_PENDING: 'FETCH_CATEGORIES_PENDING',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'FETCH_CATEGORIES_FAILED',
    FETCH_PRODUCT_PENDING: 'FETCH_PRODUCT_PENDING',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILED: 'FETCH_PRODUCT_FAILED',
    FETCH_CATEGORY_PRODUCTS_PENDING: 'FETCH_CATEGORY_PRODUCTS_PENDING',
    FETCH_CATEGORY_PRODUCTS_SUCCESS: 'FETCH_CATEGORY_PRODUCTS_SUCCESS',
    FETCH_CATEGORY_PRODUCTS_FAILED: 'FETCH_CATEGORY_PRODUCTS_FAILED',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',
    UPDATE_PRODUCT_PENDING: 'UPDATE_PRODUCT_PENDING',
}

export default CatalogActionType