const OrderActionTypes = {
    // valutare bene dove mettere sti 3
    COMPLETE_ORDER_PENDING: 'COMPLETE_ORDER_PENDING',
    COMPLETE_ORDER_SUCCESS: 'COMPLETE_ORDER_SUCCESS',
    COMPLETE_ORDER_FAILED: 'COMPLETE_ORDER_FAILED',

    FETCH_ORDER_HISTORY_SUCCESS: 'FETCH_ORDER_HISTORY_SUCCESS',
    FETCH_ORDER_HISTORY_FAILED: 'FETCH_ORDER_HISTORY_FAILED',
    FETCH_ORDER_HISTORY_PENDING: 'FETCH_ORDER_HISTORY_PENDING',
}

export default OrderActionTypes