const OrderActionTypes = {
    COMPLETE_ORDER_PENDING: 'COMPLETE_ORDER_PENDING',
    COMPLETE_ORDER_SUCCESS: 'COMPLETE_ORDER_SUCCESS',
    COMPLETE_ORDER_FAILED: 'COMPLETE_ORDER_FAILED'
}

export default OrderActionTypes